#### input ####
li_dir <- example("demoProject", "RPhosFate")
unlink(li_dir$value, recursive = TRUE)
example("DEMrelatedInput", "RPhosFate")
unlink(cv_dir, recursive = TRUE)

#### low-level interface ####
example("erosionPrerequisites", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("erosion", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("emission", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("transportPrerequisites", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("transportCalcOrder", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("transport", "RPhosFate")
unlink(cv_dir, recursive = TRUE)

#### high-level interface ####
example("RPhosFate", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("firstRun", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("subsequentRun", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("snapGauges", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("calibrationQuality", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("autoCalibrate", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("autoCalibrate2", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("saveState", "RPhosFate")
unlink(cv_dir, recursive = TRUE)

#### getters and setters ####
example("getLayer", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("getParameter", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
example("setParameter", "RPhosFate")
unlink(cv_dir, recursive = TRUE)
