# example("DEMrelatedInput", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
#
# example("erosionPrerequisites", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("erosion", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("emission", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("transportPrerequisites", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("transportCalcOrder", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("transport", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
#
# example("RPhosFate", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("firstRun", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("subsequentRun", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("snapGauges", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("calibrationQuality", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("autoCalibrate", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("saveState", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
#
# example("getLayer", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("getParameter", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
# example("setParameter", "RPhosFate", run.dontrun = TRUE)
# unlink(cv_dir, recursive = TRUE)
