// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DInfSlope
arma::dmat DInfSlope(const arma::dmat& nm_dir_inf, const arma::dmat& nm_dem, const double ns_res, const int is_ths);
RcppExport SEXP _RPhosFate_DInfSlope(SEXP nm_dir_infSEXP, SEXP nm_demSEXP, SEXP ns_resSEXP, SEXP is_thsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::dmat& >::type nm_dir_inf(nm_dir_infSEXP);
    Rcpp::traits::input_parameter< const arma::dmat& >::type nm_dem(nm_demSEXP);
    Rcpp::traits::input_parameter< const double >::type ns_res(ns_resSEXP);
    Rcpp::traits::input_parameter< const int >::type is_ths(is_thsSEXP);
    rcpp_result_gen = Rcpp::wrap(DInfSlope(nm_dir_inf, nm_dem, ns_res, is_ths));
    return rcpp_result_gen;
END_RCPP
}
// rip_inl
Rcpp::List rip_inl(const arma::dmat& nm_dir_inf, const arma::imat& im_cha, const arma::imat& im_rds, const int is_ths);
RcppExport SEXP _RPhosFate_rip_inl(SEXP nm_dir_infSEXP, SEXP im_chaSEXP, SEXP im_rdsSEXP, SEXP is_thsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::dmat& >::type nm_dir_inf(nm_dir_infSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type im_cha(im_chaSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type im_rds(im_rdsSEXP);
    Rcpp::traits::input_parameter< const int >::type is_ths(is_thsSEXP);
    rcpp_result_gen = Rcpp::wrap(rip_inl(nm_dir_inf, im_cha, im_rds, is_ths));
    return rcpp_result_gen;
END_RCPP
}
// transportCpp
Rcpp::List transportCpp(Rcpp::S4 parameters, double ns_dep_ovl, double ns_tfc_inl, Rcpp::S4 helpers, arma::imat& im_cha, arma::imat& im_dir, arma::imat& im_inl, arma::imat& im_rip, arma::dmat& nm_man, arma::dmat& nm_xxe, arma::dmat& nm_rhy, arma::dmat& nm_slp);
RcppExport SEXP _RPhosFate_transportCpp(SEXP parametersSEXP, SEXP ns_dep_ovlSEXP, SEXP ns_tfc_inlSEXP, SEXP helpersSEXP, SEXP im_chaSEXP, SEXP im_dirSEXP, SEXP im_inlSEXP, SEXP im_ripSEXP, SEXP nm_manSEXP, SEXP nm_xxeSEXP, SEXP nm_rhySEXP, SEXP nm_slpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type ns_dep_ovl(ns_dep_ovlSEXP);
    Rcpp::traits::input_parameter< double >::type ns_tfc_inl(ns_tfc_inlSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type helpers(helpersSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type im_cha(im_chaSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type im_dir(im_dirSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type im_inl(im_inlSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type im_rip(im_ripSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type nm_man(nm_manSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type nm_xxe(nm_xxeSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type nm_rhy(nm_rhySEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type nm_slp(nm_slpSEXP);
    rcpp_result_gen = Rcpp::wrap(transportCpp(parameters, ns_dep_ovl, ns_tfc_inl, helpers, im_cha, im_dir, im_inl, im_rip, nm_man, nm_xxe, nm_rhy, nm_slp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RPhosFate_DInfSlope", (DL_FUNC) &_RPhosFate_DInfSlope, 4},
    {"_RPhosFate_rip_inl", (DL_FUNC) &_RPhosFate_rip_inl, 4},
    {"_RPhosFate_transportCpp", (DL_FUNC) &_RPhosFate_transportCpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_RPhosFate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
