# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dinfRipInlCpp <- function(nm_dir_inf, im_cha, im_rds, is_ths = 1L) {
    .Call(`_RPhosFate_dinfRipInlCpp`, nm_dir_inf, im_cha, im_rds, is_ths)
}

dinfSlopeCpp <- function(nm_dir_inf, nm_dem, ns_res, is_ths = 1L) {
    .Call(`_RPhosFate_dinfSlopeCpp`, nm_dir_inf, nm_dem, ns_res, is_ths)
}

dinfTransportCpp <- function(nm_acc_inf, nm_dir_inf, nm_slp_cap, nm_man, nm_xxe, im_cha, im_rds, im_rip, im_inl, substance, parameters, helpers, is_ths = 1L) {
    .Call(`_RPhosFate_dinfTransportCpp`, nm_acc_inf, nm_dir_inf, nm_slp_cap, nm_man, nm_xxe, im_cha, im_rds, im_rip, im_inl, substance, parameters, helpers, is_ths)
}

