name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.1.2'}
          - {os: windows-latest, r: 'devel'}
          - {os: macOS-latest, r: 'oldrel'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'oldrel', rspm: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'}
          - {os: ubuntu-20.04, r: 'release', rspm: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install remotes package
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo chmod -R 777 "/opt/R"
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install dependencies (4.1.2)
        if: matrix.config.r == '4.1.2'
        run: |
          remotes::install_cran(
            c("checkmate", "hydroGOF", "raster", "Rcpp", "RcppArmadillo", "spatstat.geom", "yaml", "whitebox", "rcmdcheck"),
            repos = "https://mran.microsoft.com/snapshot/2021-12-25",
            type = "win.binary",
            dependencies = TRUE,
            lib = .libPaths()[2L]
          )
          remotes::install_deps(
            dependencies = TRUE,
            type = "win.binary",
            upgrade = "never",
            lib = .libPaths()[2L]
          )
        shell: Rscript {0}

      - name: Install dependencies (all but 4.1.2)
        if: matrix.config.r != '4.1.2'
        run: |
          remotes::install_deps(dependencies = TRUE, lib = .libPaths()[2L])
          remotes::install_cran(
            c("rgdal", "rcmdcheck", "covr"),
            lib = .libPaths()[2L]
          )
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_DONTTEST_EXAMPLES_: false
        run: |
          Rcpp::compileAttributes()
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = "--no-manual",
            check_dir = "check",
            lib = .libPaths()[2L],
            error_on = "warning"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Test coverage
        if: success() && runner.os == 'Linux' && matrix.config.r == 'release'
        run: |
          Rcpp::compileAttributes()
          covr::codecov()
        shell: Rscript {0}
